#!/bin/bash
# AutoPatch AI Platform Interactive Setup Wizard
echo "=========================================================="
echo "🔥 AutoPatch AI Platform - Interactive Setup Wizard"
echo "=========================================================="
echo "This wizard will generate your environment configuration."
echo ""

read -p "Enter Backend Server Host [Default: 0.0.0.0]: " SERVER_HOST
SERVER_HOST=${SERVER_HOST:-0.0.0.0}

read -p "Enter Backend Server Port [Default: 8000]: " SERVER_PORT
SERVER_PORT=${SERVER_PORT:-8000}

read -p "Enter SQLite Database URL [Default: sqlite:///./autopatch.db]: " DB_URL
DB_URL=${DB_URL:-sqlite:///./autopatch.db}

# Generate a secure random token if the user doesn't provide one
RANDOM_TOKEN=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)
read -p "Enter Secret Key / Agent Auth Token [Default: $RANDOM_TOKEN]: " SECRET_KEY
SECRET_KEY=${SECRET_KEY:-$RANDOM_TOKEN}

echo ""
echo "Writing configuration to .env..."

cat <<EOF > .env
# AutoPatch AI Platform Environment Config - GENERATED BY SETUP WIZARD

# Backend Configuration
AUTOPATCH_SERVER_HOST=$SERVER_HOST
AUTOPATCH_SERVER_PORT=$SERVER_PORT
DATABASE_URL=$DB_URL
SECRET_KEY=$SECRET_KEY

# Agent Configuration
AUTOPATCH_SERVER_URL=http://127.0.0.1:$SERVER_PORT
AGENT_AUTH_TOKEN=$SECRET_KEY
AGENT_HEARTBEAT_INTERVAL=30
AGENT_DISCOVERY_INTERVAL=300
AGENT_EXECUTOR_INTERVAL=15
AGENT_MONITORING_INTERVAL=60

# Frontend Configuration
NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:$SERVER_PORT
EOF

echo "Done! The .env file has been configured securely."
echo "You can now run ./deploy.sh to install dependencies, and ./startup.sh to begin orchestration."
echo "=========================================================="
